services:
  api-gateway:
    image: api-gateway
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - '5000:8080'
      - '8081:8081'
  auth-api:
    image: auth
    build:
      context: ./Auth
      dockerfile: Dockerfile
    ports:
      - '5001:8080'
    depends_on:
      postgres:
        condition: service_healthy
  product-management-api:
    image: product-management
    build:
      context: ./ProductManagement
      dockerfile: Dockerfile
    ports:
      - '5002:8080'
    depends_on:
      postgres:
        condition: service_healthy
  order-management-api:
    image: order-management
    build:
      context: ./OrderManagement
      dockerfile: Dockerfile
    ports:
      - '5003:8080'
    depends_on:
      postgres:
        condition: service_healthy
  cart-api:
    image: cart
    build:
      context: ./Cart
      dockerfile: Dockerfile
    ports:
      - '5004:8080'
  payment-api:
    image: payment
    build:
      context: ./Payment
      dockerfile: Dockerfile
    ports:
      - '5005:8080'
    depends_on:
      postgres:
        condition: service_healthy
  inventory-api:
    image: inventory
    build:
      context: ./Inventory
      dockerfile: Dockerfile
    ports:
      - '5006:8080'
    depends_on:
      postgres:
        condition: service_healthy
  profile-api:
    image: profile
    build:
      context: ./Profile
      dockerfile: Dockerfile
    ports:
      - '5007:8080'
    depends_on:
      postgres:
        condition: service_healthy
  shipping-api:
    image: shipping
    build:
      context: ./Shipping
      dockerfile: Dockerfile
    ports:
      - '5008:8080'
  notification-api:
    image: notification
    build:
      context: ./Notification 
      dockerfile: Dockerfile
    ports:
      - '5009:8080'
  postgres:
    image: 'postgres:15'
    restart: on-failure
    ports:
      - '5432:5432'
    volumes:
      - ./Data/Database/Data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  object-store:
    image: 'minio/minio:RELEASE.2025-04-22T22-12-26Z'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - type: bind
        source: ./Data/Object-store
        target: /data
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${OBJECT_STORE_USER}
      MINIO_ROOT_PASSWORD: ${OBJECT_STORE_PASSWORD}
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_JMXPORT: 9997