<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>0.6.35</Version>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Authors>Mark Marada</Authors>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>EcommerceLib</PackageId>
        <Description>My awesome library</Description>
        <RootNamespace>EcommerceLib</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Confluent.Kafka" Version="2.11.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.20" />
      <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
      <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.3.0" />
      <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
      <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.19" />
      <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.8" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
      <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.8" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.8" />
      <PackageReference Include="Minio" Version="6.0.5" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="Respawn" Version="6.2.1" />
    <PackageReference Include="Testcontainers" Version="4.7.0" />
    <PackageReference Include="Testcontainers.Kafka" Version="4.7.0" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.7.0" />
    <PackageReference Include="WireMock.Net" Version="1.6.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Testing\" />
    </ItemGroup>

</Project>
